server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
      - application/json
client:
  os_message_bus_routing_service_address: ${OS_MESSAGE_BUS_ROUTING_SERVICE_ADDRESS:https://prod-cn1.api.1stepai.cn/os-messagebus-routing-service/}


opentracing:
  jaeger:
    log-spans: true
    enabled: true
    http-sender:
      url: ${JAEGER_COLLECTOR_ADDRESS:http://jaeger-collector.default.svc.cluster.local:14268/api/traces}
    probabilistic-sampler:
      sampling-rate: 0.2

proxy:
  base_path: ${PROXY_PATH:}
  host_path: ${HOST_PATH:}
  http_proxy_host: ${HTTP_PROXY_HOST:}
  http_proxy_port: ${HTTP_PROXY_PORT:}

spring:
  application:
    name: os-messagebus-service
  baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:}
    port: ${RABBITMQ_PORT:}
    username: ${RABBITMQ_USERNAME:}
    password: ${RABBITMQ_PASSWORD:}

domain: ${DOMAIN:dev}
marketplace: ${MARKETPLACE:}

debug:
  log_on: ${DEBUG_LOG_ON:}

logbackpath: ${LOGBACK_PATH:}

terminal:
  customer_id: ${CUSTOMER_ID:}
  terminal_id: ${TERMINAL_ID:}
  secure_key: ${SECURE_KEY:}
  consumer:
    consumer_type: ${CONSUMER_TYPE:}
    exchange_name: ${CONSUMER_EXCHANGE_NAME:}
    address: ${CONSUMER_ADDRESS:}
    port: ${CONSUMER_PORT:}
    username: ${CONSUMER_USERNAME:}
    password: ${ECONSUMER_PASSWORDXCHANGE_NAME:}
    concurrency: ${CONSUMER_CONCURRENCY:}
    acknowledgeMode: ${CONSUMER_ACKNOWLEDGE_MODEL:}
    maxConcurrency: ${CONSUMER_MAX_CONCURRENCY:}
    prefetch: ${PREFETCH:}
  run_mode: ${RUN_MODE:}
  server:
    url: ${NETTY_SERVER_HOST:}
    port: ${NETTY_SERVER_PORT:}
  client:
    port: ${NETTY_CLIENT_PORT:}